services:
  backend:
    build:
      context: ./backend/MyApp.Api
      dockerfile: Dockerfile
    ports:
      - "5029:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Map the .env keys to the container environment
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}


  frontend:
    build:
      context: ./frontend/myapp-front
      dockerfile: Dockerfile
      args:
        ANGULAR_ENV: ${ANGULAR_ENV:-production}
    ports:
      - "4200:80"
    depends_on:
      - backend